'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class KWSimple

    '''<summary>
    '''PNameTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PNameTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PZipTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PZipTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ElevationTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ElevationTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator1 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''FireplacetypeDD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FireplacetypeDD As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''FireplaceATxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FireplaceATxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator2 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''FireplaceBTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FireplaceBTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator3 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''DepthSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DepthSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''FireplaceCTXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FireplaceCTXT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator4 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''ChimneytypeDD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChimneytypeDD As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''WoodRdo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WoodRdo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''GasRdo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GasRdo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ChimneyATxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChimneyATxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator6 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''HeightTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeightTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator7 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''El90Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents El90Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator8 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''El45Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents El45Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator12 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''El30Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents El30Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator9 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''NumberoffluesDD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NumberoffluesDD As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''OffsetTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OffsetTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator11 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CalcBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalcBtn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Print control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Print As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Fireplaceimg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fireplaceimg As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''FanSelectionLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FanSelectionLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ExhaustCFMLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExhaustCFMLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlueCFMLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlueCFMLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ExhaustPressureLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExhaustPressureLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FlueVelLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlueVelLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MACFMLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MACFMLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MAFanSelectionLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MAFanSelectionLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''errorchklbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errorchklbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FanImg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FanImg As Global.System.Web.UI.WebControls.Image
End Class
