'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class KWSimplePrint

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''logo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logo As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblProjectName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProjectZipCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectZipCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblElevation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblElevation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFireplaceType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFireplaceType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFireplaceWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFireplaceWidth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFireplaceHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFireplaceHeight As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFireplaceDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFireplaceDepth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFlueType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFlueType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFuelType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFuelType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFlueDiameter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFlueDiameter As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFlueHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFlueHeight As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFlue90Elbow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFlue90Elbow As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFlue45Elbow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFlue45Elbow As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFlue30Elbow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFlue30Elbow As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumberOfFlues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumberOfFlues As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOffsetLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOffsetLength As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExhaustFanSelection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExhaustFanSelection As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalExhaustCFM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalExhaustCFM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExhaustCFMFlue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExhaustCFMFlue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDraft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDraft As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVelocityFlue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVelocityFlue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMakeupAirCFM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMakeupAirCFM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMakeupAirFan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMakeupAirFan As Global.System.Web.UI.WebControls.Label
End Class
