'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Calculator

    '''<summary>
    '''PNameTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PNameTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''PCitytxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PCitytxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Plocationtxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Plocationtxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''PForTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PForTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PCompanyTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PCompanyTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MaxInputTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MaxInputTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator1 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CO2Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CO2Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator5 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CheckBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CFMTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CFMTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CFMTxt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CFMTxt2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MinInputTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MinInputTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator2 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''AmbientTempTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AmbientTempTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator6 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''MaxTempTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MaxTempTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator3 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''AltitudeTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AltitudeTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator7 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''MinTempTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MinTempTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator4 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''MaxPressureTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MaxPressureTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator8 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''MinPressureTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MinPressureTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator9 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CADuctLengthTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CADuctLengthTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator10 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CAWyeTeeTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAWyeTeeTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator11 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CA90TeeTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CA90TeeTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator12 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CA45TeeTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CA45TeeTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator13 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CA15ElTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CA15ElTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator18 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CA30ElTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CA30ElTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator19 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CA45ElTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CA45ElTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator20 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CA90ElTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CA90ElTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator21 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CAIncreaser1Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAIncreaser1Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator15 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CAIncreaser2Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAIncreaser2Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator14 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CAReducer1Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAReducer1Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator16 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CAReducer2Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAReducer2Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator17 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CAAPLTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAAPLTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator22 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''ScreenRdo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScreenRdo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Gooseneck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Gooseneck As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''CADiameterTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CADiameterTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator23 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CASCFMTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CASCFMTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator24 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CAMaxPressureTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAMaxPressureTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator25 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CAMinPRessureTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAMinPRessureTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator26 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CACONDuctLengthTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CACONDuctLengthTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CACON90TeeTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CACON90TeeTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CACON45TeeTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CACON45TeeTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CACONBaffleTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CACONBaffleTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CACON15ElTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CACON15ElTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CACON30ElTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CACON30ElTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CACON45ELTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CACON45ELTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CACON90ELTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CACON90ELTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CACONDiameterTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CACONDiameterTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CACONARTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CACONARTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CACONSCFMTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CACONSCFMTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ExHeightTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExHeightTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator27 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''ExLengthTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExLengthTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator28 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Ex90TeeTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ex90TeeTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator29 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''ExBootTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExBootTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator30 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Ex15ElTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ex15ElTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator37 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Ex30ElTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ex30ElTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator38 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Ex45ElTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ex45ElTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator39 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Ex90ElTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ex90ElTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator40 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''ExIDTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExIDTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator31 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''ExIncreaser1Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExIncreaser1Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator32 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''ExIncrease2Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExIncrease2Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator33 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''ExReducer1Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExReducer1Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator41 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''ExReducer2Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExReducer2Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator42 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''ExBAroTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExBAroTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator34 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''ExBaffleTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExBaffleTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator43 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Miter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Miter As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Box control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Box As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Elbow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Elbow As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RainCap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RainCap As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ExitCone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExitCone As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ExARTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExARTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator35 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''EXDiameterTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXDiameterTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator44 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''EXAPLTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXAPLTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RangeValidator36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidator36 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''EXCONMaxInputTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXCONMaxInputTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EXCONMinInputTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXCONMinInputTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EXCONVerticalTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXCONVerticalTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EXCONLengthTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXCONLengthTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EXCON45TeeTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXCON45TeeTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EXCON15ElTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXCON15ElTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EXCON30ELTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXCON30ELTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EXCONDiameterTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXCONDiameterTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EXCONBAffleTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXCONBAffleTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EXCONARTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXCONARTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EXConMinTempTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConMinTempTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EXConMaxTempTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConMaxTempTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EXConCO2Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConCO2Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''MaxCFMTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MaxCFMTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MinCFMTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MinCFMTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalculateBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalculateBtn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CASelectedDiameterLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CASelectedDiameterLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CASelectedCFMLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CASelectedCFMLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CASelectedVelocityLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CASelectedVelocityLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CASelectedDensityLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CASelectedDensityLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CASelectedTotalKLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CASelectedTotalKLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CASelectedPLLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CASelectedPLLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CASelTPLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CASelTPLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AmbientTempLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AmbientTempLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CASizedDiameterLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CASizedDiameterLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CASizedCFMLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CASizedCFMLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CASizedVelocityLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CASizedVelocityLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CASizedDensityLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CASizedDensityLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CASizedTotalKLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CASizedTotalKLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CASizedPLLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CASizedPLLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CASizTPLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CASizTPLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mbientTempLbl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mbientTempLbl2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CAConDiameterLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAConDiameterLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CAConCFMLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAConCFMLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CAConVelocityLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAConVelocityLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CAConDensityLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAConDensityLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CAConTotalKLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAConTotalKLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CAConDPLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAConDPLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CAConTPLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAConTPLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CAConTempLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAConTempLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSelDiaLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSelDiaLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSelHiCFMLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSelHiCFMLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSelHiVelLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSelHiVelLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSelHiDenLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSelHiDenLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSelHiKLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSelHiKLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSelHiPLLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSelHiPLLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSelHiDtLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSelHiDtLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSelHiTPLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSelHiTPLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SelMaxTempLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelMaxTempLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ExSelDiaLbl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExSelDiaLbl2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSelLoCFMLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSelLoCFMLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSelLoVelLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSelLoVelLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSelLoDenLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSelLoDenLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSelLoKLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSelLoKLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSelLoPLLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSelLoPLLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSelLoDtLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSelLoDtLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSelLoTPLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSelLoTPLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SelMinTempLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelMinTempLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSizDiaLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSizDiaLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSizHiCFMLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSizHiCFMLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSizHiVelLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSizHiVelLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSizHiDenLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSizHiDenLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSizHiKLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSizHiKLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSizHiPLLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSizHiPLLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSizHiDtLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSizHiDtLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSizHiTPLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSizHiTPLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SizMaxTempLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SizMaxTempLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSizDiaLbl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSizDiaLbl2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSizLoCFMLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSizLoCFMLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSizLoVelLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSizLoVelLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSizLoDenLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSizLoDenLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSizLoKLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSizLoKLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSizLoPLLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSizLoPLLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSizLoDtLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSizLoDtLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXSizLoTPLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXSizLoTPLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SizMinTempLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SizMinTempLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXConDiaLbl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConDiaLbl1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXConMaxCFMLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConMaxCFMLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXConMaxVelLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConMaxVelLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXConDen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConDen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXCONMaxTKLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXCONMaxTKLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXConMaxDPLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConMaxDPLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXConHighDraftLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConHighDraftLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXConHighTPLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConHighTPLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXConHighTempLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConHighTempLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXConDiaLbl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConDiaLbl2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXConMinCFMLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConMinCFMLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXConMinVelLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConMinVelLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXConDenLbl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConDenLbl2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXConMinTKLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConMinTKLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXConMinDPLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConMinDPLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXConLowDraftLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConLowDraftLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXConLowTPLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConLowTPLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EXConLowTempLBL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXConLowTempLBL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SelTPLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelTPLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SizTPLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SizTPLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LinkButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButton1 As Global.System.Web.UI.WebControls.LinkButton
End Class
